import React, { useState } from 'react';
import { 
  Shield, 
  Phone, 
  Coffee, 
  Heart, 
  X, 
  Calendar, 
  Clock, 
  Mail, 
  MessageSquare, 
  Check, 
  CheckCircle,
  ChevronRight,
  ChevronLeft,
  User,
  Activity,
  UserCheck,
  Hourglass
} from 'lucide-react';

const PREMIUM_SERVICES = [
  // {
  //   id: 'medical_care',
  //   title: 'Medical Care & Hospitalization',
  //   icon: Shield,
  //   color: 'emerald',
  //   subtypes: [
  //     'Post-Hospitalization Rehabilitation',
  //     'Geriatric Acute Medical Care',
  //     'Chronic Illness Supervision',
  //     'Hospitalization Companion & Escort'
  //   ]
  // },
  {
    id: 'home_nurses',
    title: 'Home Nurses',
    icon: Phone,
    color: 'emerald',
    subtypes: [
      '24/7 Registered Nurse (RN)',
      '12-Hour Day/Night Duty Nurse',
      'Wound Dressing & Injection Care',
      'Palliative & ICU-at-Home Nursing'
    ]
  },
  {
    id: 'doctor_consultation',
    title: 'Doctor Consultation & Physio',
    icon: Coffee,
    color: 'emerald',
    subtypes: [
      'General Physician Home Consultation',
      'Orthopedic Physiotherapy',
      'Neurological Rehab Therapist',
      'Geriatrician Virtual Consultation'
    ]
  },
  {
    id: 'daily_assistance',
    title: 'Daily Assistance',
    icon: Heart,
    color: 'emerald',
    subtypes: [
      'Personal Hygiene & Bathing Assist',
      'Healthy Meal Prep & Nutrition Support',
      'Mobility & Safe Transfer Assistance',
      'Light Housekeeping & Laundry'
    ]
  },
  {
    id: 'caregiver_attendants',
    title: 'Caregiver & Attendants',
    icon: Shield,
    color: 'emerald',
    subtypes: [
      'Certified Dementia Attendant',
      'Full-time Bedridden Patient Attendant',
      'Day-time Companion Caregiver',
      'Night Supervision Attendant'
    ]
  },
  {
    id: 'companionship_engagement',
    title: 'Companionship & Engagement',
    icon: Coffee,
    color: 'emerald',
    subtypes: [
      'Cognitive Games & Mental Exercise',
      'Outdoor Walking & Social Escort',
      'Reading, Arts & Hobby Mentorship',
      'Reminiscence & Conversation Companion'
    ]
  },
  {
    id: 'helping_hands_errands',
    title: 'Helping Hands & Errands',
    icon: Phone,
    color: 'emerald',
    subtypes: [
      'Pharmacy & Medication Pick-up',
      'Grocery Shopping & Bank Errands',
      'Utility Bills & Tech Assistance',
      'Light Gardening & Home Coordination'
    ]
  }
];

const PremiumServices = () => {
  const [selectedService, setSelectedService] = useState(null);
  const [activeStep, setActiveStep] = useState(0);
  const [formData, setFormData] = useState({
    needDescription: '',
    subtype: '',
    startDate: '',
    startTimeRange: '08:00 AM - 09:00 AM',
    bookingHours: '4 Hours',
    preferredContactTime: 'Anytime',
    contactMode: 'Phone Call',
    contactNumber: '',
    emailAddress: ''
  });
  
  const [errors, setErrors] = useState({});
  // Snapshot of the confirmed booking (incl. autogenerated service ID)
  // rendered on the final "Booking Details" tab after Confirm Request
  const [confirmedBooking, setConfirmedBooking] = useState(null);

  // Autogenerated service ID: first 2 letters of the service type/title
  // followed by 6 random digits (e.g. "ME483920")
  const generateServiceId = (serviceType) => {
    const prefix = (serviceType || '').replace(/[^A-Za-z]/g, '').slice(0, 2).toUpperCase();
    return `${prefix}${Math.floor(100000 + Math.random() * 900000)}`;
  };

  // Defining the four stages of our custom multimodal popup configuration
  const modalSteps = [
    { label: 'Care Profile', desc: 'Define your care needs & subtype.' },
    { label: 'Timing & Schedule', desc: 'Pick target start date & time window.' },
    { label: 'Contact Preferences', desc: 'Choose timing & outreach channel.' },
    { label: 'Verify & Confirm', desc: 'Provide contact information.' },
    { label: 'Confirmed', desc: 'Booking summary & service ID.' }
  ];

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  const handleServiceSelect = (service) => {
    setSelectedService(service);
    setActiveStep(0);
    setFormData({
      needDescription: '',
      subtype: service.subtypes[0],
      startDate: new Date().toISOString().split('T')[0], // Default to today
      startTimeRange: '08:00 AM - 09:00 AM',
      bookingHours: '4 Hours',
      preferredContactTime: 'Anytime',
      contactMode: 'Phone Call',
      contactNumber: '',
      emailAddress: ''
    });
    setErrors({});
    setConfirmedBooking(null);
  };

  const handleNextStep = () => {
    if (activeStep < modalSteps.length - 2) {
      setActiveStep(prev => prev + 1);
    } else {
      // "Confirm Request" on the final input step -> validate & show details
      submitModalRequest();
    }
  };

  const handlePrevStep = () => {
    if (activeStep > 0) {
      setActiveStep(prev => prev - 1);
    }
  };

  const submitModalRequest = () => {
    const newErrors = {};

    // Validate the mandatory phone input field on the final step
    if (!formData.contactNumber.trim()) {
      newErrors.contactNumber = 'Contact number is required';
    } else if (!/^[+0-9\s-]{8,15}$/.test(formData.contactNumber.trim())) {
      newErrors.contactNumber = 'Please enter a valid phone number';
    }

    if (formData.emailAddress.trim() && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.emailAddress.trim())) {
      newErrors.emailAddress = 'Please enter a valid email address';
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // Advance to the final "Booking Details" tab instead of closing the
    // modal: snapshot the complete booking incl. autogenerated service ID
    setConfirmedBooking({
      serviceId: generateServiceId(selectedService.title),
      serviceTitle: selectedService.title,
      subtype: formData.subtype,
      startDate: formData.startDate,
      startTimeRange: formData.startTimeRange,
      bookingHours: formData.bookingHours,
      contactMode: formData.contactMode,
      contactNumber: formData.contactNumber,
      emailAddress: formData.emailAddress
    });
    setActiveStep(modalSteps.length - 1);
  };

  const START_TIMES = [
    '08:00 AM - 09:00 AM',
    '09:00 AM - 10:00 AM',
    '10:00 AM - 11:00 AM',
    '11:00 AM - 12:00 PM',
    '12:00 PM - 01:00 PM',
    '01:00 PM - 02:00 PM',
    '02:00 PM - 03:00 PM',
    '03:00 PM - 04:00 PM',
    '04:00 PM - 05:00 PM',
    '05:00 PM - 06:00 PM',
    '06:00 PM - 07:00 PM',
    '07:00 PM - 08:00 PM'
  ];

  const BOOKING_HOURS_OPTIONS = [
    '1 Hour',
    '2 Hours',
    '4 Hours',
    '8 Hours',
    '12 Hours (Half Day)',
    '24 Hours (Full Day)'
  ];

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800 font-sans antialiased selection:bg-emerald-100">
      
      {/* Main Container mirroring image_f7e8e7.png */}
      <div className="max-w-7xl mx-auto px-6 py-16 md:py-24">
        <div className="mb-12">
          <h1 className="text-4xl md:text-[44px] font-serif text-slate-900 font-normal leading-tight tracking-tight mb-3">
            Premium Services
          </h1>
          <p className="text-slate-500 text-lg md:text-xl font-light">
            Personalized care services tailored to your needs
          </p>
        </div>

        {/* Responsive Grid mapping card styles */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {PREMIUM_SERVICES.map((service) => {
            const IconComponent = service.icon;
            return (
              <button
                key={service.id}
                onClick={() => handleServiceSelect(service)}
                className="group flex flex-col items-center justify-center p-8 bg-white border border-slate-100 rounded-[28px] shadow-sm hover:shadow-md hover:border-emerald-500/20 transition-all duration-300 min-h-[220px] text-center focus:outline-none focus:ring-2 focus:ring-emerald-500/30"
              >
                <div className="w-16 h-16 rounded-full bg-emerald-50/60 text-[#13a89e] flex items-center justify-center mb-6 group-hover:scale-105 transition-transform duration-300">
                  <IconComponent size={24} className="stroke-[1.75]" />
                </div>
                <h3 className="text-slate-800 font-bold text-base tracking-tight leading-snug px-3 group-hover:text-[#1c5a4b] transition-colors">
                  {service.title}
                </h3>
              </button>
            );
          })}
        </div>
      </div>

      {}
      {selectedService && (
        <div 
          className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-sm flex items-center justify-center p-4 transition-all duration-300"
          onClick={() => setSelectedService(null)}
        >
          <div 
            className="bg-white w-full max-w-xl rounded-[40px] shadow-2xl flex flex-col max-h-[90vh] overflow-hidden animate-in zoom-in-95 duration-300"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header containing Progress Segment Indicators */}
            <div className="px-8 pt-8 pb-6 border-b border-slate-100">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-2xl bg-emerald-50 text-[#1c5a4b] flex items-center justify-center shadow-inner">
                    {React.createElement(selectedService.icon, { size: 20 })}
                  </div>
                  <div>
                    <span className="text-[10px] font-black text-emerald-600 uppercase tracking-widest block">Configure Request</span>
                    <h3 className="text-xl font-bold text-slate-900 leading-tight">{selectedService.title}</h3>
                  </div>
                </div>
                <button 
                  onClick={() => setSelectedService(null)}
                  className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-50 rounded-full transition-all"
                >
                  <X size={20} />
                </button>
              </div>

              {/* Segmented Progress Bar */}
              <div className="flex gap-2">
                {modalSteps.map((step, idx) => (
                  <div key={idx} className="flex-1 space-y-2">
                    <div 
                      className={`h-1.5 rounded-full transition-all duration-500 ${
                        idx <= activeStep ? 'bg-[#1c5a4b]' : 'bg-slate-100'
                      }`} 
                    />
                    <p className={`text-[9px] font-black uppercase text-center tracking-wider ${
                      idx === activeStep ? 'text-[#1c5a4b]' : 'text-slate-300'
                    }`}>
                      {step.label}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Modal Scrollable Form Body */}
            <div className="flex-1 overflow-y-auto px-8 py-6">
              
              {/* STEP 1: Care Need & Subtype Details */}
              {activeStep === 0 && (
                <div className="space-y-6 animate-in slide-in-from-right-8 duration-300">
                  <div className="bg-emerald-50/40 p-4 rounded-2xl border border-emerald-100/30 flex items-start gap-3">
                    <Activity size={18} className="text-[#1c5a4b] shrink-0 mt-0.5" />
                    <p className="text-xs text-slate-600 leading-relaxed font-medium">
                      Select the matching service sub-type and describe any customized preferences or physical/cognitive assistance needed.
                    </p>
                  </div>

                  <div className="space-y-2">
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider">Respective Care Sub-Type</label>
                    <div className="relative">
                      <select 
                        name="subtype"
                        value={formData.subtype}
                        onChange={handleInputChange}
                        className="w-full px-4 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:ring-2 focus:ring-emerald-500 focus:bg-white outline-none text-sm font-bold text-slate-700 transition-all appearance-none cursor-pointer"
                      >
                        {selectedService.subtypes.map((sub, idx) => (
                          <option key={idx} value={sub}>{sub}</option>
                        ))}
                      </select>
                      <div className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none">
                        <ChevronRight size={16} className="rotate-90" />
                      </div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider">Mention Your Need</label>
                    <textarea 
                      name="needDescription"
                      rows="4"
                      value={formData.needDescription}
                      onChange={handleInputChange}
                      placeholder="Tell us about the client's current health status, recovery state, daily patterns, or specific custom instructions..."
                      className="w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-2xl focus:ring-2 focus:ring-emerald-500 focus:bg-white outline-none transition-all text-sm font-medium text-slate-800 placeholder:text-slate-400 leading-relaxed"
                    />
                  </div>
                </div>
              )}

              {/* STEP 2: Timing, Start Time & Booking Hours Selection */}
              {activeStep === 1 && (
                <div className="space-y-6 animate-in slide-in-from-right-8 duration-300">
                  <div className="space-y-2">
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5">
                      <Calendar size={14} className="text-slate-400" /> Expected Start Date
                    </label>
                    <input 
                      type="date"
                      name="startDate"
                      value={formData.startDate}
                      onChange={handleInputChange}
                      className="w-full px-4 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:ring-2 focus:ring-emerald-500 focus:bg-white outline-none text-sm text-slate-800 font-bold"
                    />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Start Time 1-hour ranges */}
                    <div className="space-y-2">
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5">
                        <Clock size={14} className="text-slate-400" /> Start Time (1hr Range)
                      </label>
                      <div className="relative">
                        <select 
                          name="startTimeRange"
                          value={formData.startTimeRange}
                          onChange={handleInputChange}
                          className="w-full px-4 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:ring-2 focus:ring-emerald-500 focus:bg-white outline-none text-sm text-slate-800 font-bold appearance-none cursor-pointer"
                        >
                          {START_TIMES.map((time, idx) => (
                            <option key={idx} value={time}>{time}</option>
                          ))}
                        </select>
                        <div className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none">
                          <ChevronRight size={16} className="rotate-90" />
                        </div>
                      </div>
                    </div>

                    {/* Booking Hours */}
                    <div className="space-y-2">
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5">
                        <Hourglass size={14} className="text-slate-400" /> Booking Hours
                      </label>
                      <div className="relative">
                        <select 
                          name="bookingHours"
                          value={formData.bookingHours}
                          onChange={handleInputChange}
                          className="w-full px-4 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:ring-2 focus:ring-emerald-500 focus:bg-white outline-none text-sm text-slate-800 font-bold appearance-none cursor-pointer"
                        >
                          {BOOKING_HOURS_OPTIONS.map((hours, idx) => (
                            <option key={idx} value={hours}>{hours}</option>
                          ))}
                        </select>
                        <div className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none">
                          <ChevronRight size={16} className="rotate-90" />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* STEP 3: Contact preferences */}
              {activeStep === 2 && (
                <div className="space-y-6 animate-in slide-in-from-right-8 duration-300">
                  <div className="space-y-3">
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider">Contact Mode</label>
                    <div className="grid grid-cols-2 gap-3">
                      {['Phone Call', 'WhatsApp'].map(mode => (
                        <label 
                          key={mode} 
                          className={`flex flex-col items-center justify-center p-6 border rounded-[28px] text-xs font-bold cursor-pointer transition-all ${
                            formData.contactMode === mode 
                            ? 'border-[#1c5a4b] bg-emerald-50/50 text-[#1c5a4b]' 
                            : 'border-slate-100 bg-slate-50 text-slate-500 hover:border-slate-200'
                          }`}
                        >
                          <input 
                            type="radio" 
                            name="contactMode" 
                            value={mode}
                            checked={formData.contactMode === mode}
                            onChange={handleInputChange}
                            className="hidden" 
                          />
                          <div className="w-10 h-10 rounded-full bg-white flex items-center justify-center mb-3 text-slate-400 shadow-sm border border-slate-50">
                            {mode === 'WhatsApp' ? <MessageSquare size={16} /> : <Phone size={16} />}
                          </div>
                          <span>{mode}</span>
                        </label>
                      ))}
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider">Preferred Contact Time</label>
                    <select 
                      name="preferredContactTime"
                      value={formData.preferredContactTime}
                      onChange={handleInputChange}
                      className="w-full px-4 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:ring-2 focus:ring-emerald-500 focus:bg-white outline-none text-sm text-slate-800 font-bold cursor-pointer"
                    >
                      <option>Anytime</option>
                      <option>Morning (09:00 AM - 12:00 PM)</option>
                      <option>Afternoon (12:00 PM - 04:00 PM)</option>
                      <option>Evening (04:00 PM - 07:00 PM)</option>
                    </select>
                  </div>
                </div>
              )}

              {/* STEP 4: Mandatory Information Verification & Summary */}
              {activeStep === 3 && (
                <div className="space-y-6 animate-in slide-in-from-right-8 duration-300">
                  <div className="p-5 bg-slate-50 rounded-3xl border border-slate-100 space-y-3">
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Configuration Summary</p>
                    <div className="grid grid-cols-2 gap-4 text-xs font-bold">
                      <div>
                        <span className="text-slate-400 block mb-0.5">Subtype:</span>
                        <span className="text-slate-700">{formData.subtype}</span>
                      </div>
                      <div>
                        <span className="text-slate-400 block mb-0.5">Start Date:</span>
                        <span className="text-slate-700">{formData.startDate}</span>
                      </div>
                      <div>
                        <span className="text-slate-400 block mb-0.5">Start Time:</span>
                        <span className="text-slate-700">{formData.startTimeRange}</span>
                      </div>
                      <div>
                        <span className="text-slate-400 block mb-0.5">Booking Duration:</span>
                        <span className="text-slate-700">{formData.bookingHours}</span>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <div className="flex justify-between items-center">
                      <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider">
                        Contact Number <span className="text-red-500">*</span>
                      </label>
                      <span className="text-[10px] text-red-500 font-bold uppercase tracking-wider">Mandatory</span>
                    </div>
                    <div className="relative">
                      <input 
                        type="tel"
                        name="contactNumber"
                        value={formData.contactNumber}
                        onChange={handleInputChange}
                        placeholder="Enter phone number"
                        className={`w-full px-5 py-4 bg-slate-50 border rounded-2xl focus:ring-2 focus:ring-emerald-500 focus:bg-white outline-none text-sm font-bold transition-all ${
                          errors.contactNumber ? 'border-red-400 focus:ring-red-100' : 'border-slate-100'
                        }`}
                      />
                      <div className="absolute right-5 top-1/2 -translate-y-1/2 text-slate-400">
                        <Phone size={16} />
                      </div>
                    </div>
                    {errors.contactNumber && (
                      <p className="text-xs font-semibold text-red-500 mt-1 pl-1">{errors.contactNumber}</p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider">Email Address</label>
                    <div className="relative">
                      <input 
                        type="email"
                        name="emailAddress"
                        value={formData.emailAddress}
                        onChange={handleInputChange}
                        placeholder="yourname@domain.com"
                        className={`w-full px-5 py-4 bg-slate-50 border rounded-2xl focus:ring-2 focus:ring-emerald-500 focus:bg-white outline-none text-sm font-bold transition-all ${
                          errors.emailAddress ? 'border-red-400 focus:ring-red-100' : 'border-slate-100'
                        }`}
                      />
                      <div className="absolute right-5 top-1/2 -translate-y-1/2 text-slate-400">
                        <Mail size={16} />
                      </div>
                    </div>
                    {errors.emailAddress && (
                      <p className="text-xs font-semibold text-red-500 mt-1 pl-1">{errors.emailAddress}</p>
                    )}
                  </div>
                </div>
              )}

              {/* STEP 5: Booking Confirmation — autogenerated service ID + details */}
              {activeStep === modalSteps.length - 1 && confirmedBooking && (
                <div className="space-y-5 animate-in fade-in slide-in-from-right-8 duration-300">
                  {/* Success header */}
                  <div className="flex flex-col items-center text-center pt-1 pb-1">
                    <div className="w-14 h-14 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center mb-3">
                      <CheckCircle size={28} strokeWidth={2.25} />
                    </div>
                    <h3 className="text-xl font-serif font-bold text-slate-900">Request Confirmed!</h3>
                    <p className="text-xs text-slate-500 mt-1">Your Premium Services booking has been registered successfully.</p>
                  </div>

                  {/* Autogenerated Service ID */}
                  <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-4 flex items-center justify-between gap-3">
                    <span className="text-[10px] font-black uppercase tracking-widest text-emerald-700">Service ID</span>
                    <span className="font-mono font-bold text-base tracking-[0.15em] text-[#1c5a4b]">{confirmedBooking.serviceId}</span>
                  </div>

                  {/* Booking details summary */}
                  <div className="border border-slate-100 rounded-2xl overflow-hidden">
                    <p className="px-4 py-2.5 bg-slate-50 border-b border-slate-100 text-[10px] font-black uppercase tracking-widest text-slate-500">Booking Details</p>
                    <dl className="divide-y divide-slate-50">
                      {[
                        ['Service', confirmedBooking.serviceTitle],
                        ['Sub-Type', confirmedBooking.subtype],
                        ['Start Date', confirmedBooking.startDate],
                        ['Time Window', confirmedBooking.startTimeRange],
                        ['Duration', confirmedBooking.bookingHours],
                        ['Contact Mode', confirmedBooking.contactMode],
                        ['Phone Number', confirmedBooking.contactNumber],
                        ['Email Address', confirmedBooking.emailAddress || '\u2014']
                      ].map(([label, value]) => (
                        <div key={label} className="flex items-start justify-between gap-4 px-4 py-2.5">
                          <dt className="text-xs font-bold text-slate-400 uppercase tracking-wider shrink-0">{label}</dt>
                          <dd className="text-xs font-semibold text-slate-800 text-right break-words">{value}</dd>
                        </div>
                      ))}
                    </dl>
                  </div>

                  {/* Close button — dismisses the popup
                  <button
                    type="button"
                    onClick={() => setSelectedService(null)}
                    className="w-full bg-[#1c5a4b] hover:bg-[#16473b] text-white py-4 rounded-2xl font-bold text-sm shadow-lg shadow-[#1c5a4b]/20 transition-all flex items-center justify-center gap-2"
                  >
                    Close <X size={16} />
                  </button> */}
                </div>
              )}

            </div>

            {/* Sticky Action Footer controls based on current state */}
            {/* Sticky Action Footer controls — hidden on the final "Confirmed"
                tab, which already provides its own Close button at the end */}
            {activeStep !== modalSteps.length - 1 && (
            <div className="p-8 border-t border-slate-100 bg-white flex gap-4">
              {activeStep > 0 ? (
                <button 
                  type="button"
                  onClick={handlePrevStep}
                  className="flex-1 bg-slate-50 hover:bg-slate-100 text-slate-600 py-4 rounded-2xl font-bold text-sm transition-all flex items-center justify-center gap-2 border border-slate-100"
                >
                  <ChevronLeft size={16} /> Back
                </button>
              ) : (
                <button 
                  type="button"
                  onClick={() => setSelectedService(null)}
                  className="flex-1 bg-slate-100 hover:bg-slate-200 text-slate-600 py-4 rounded-2xl font-bold text-sm transition-all"
                >
                  Cancel
                </button>
              )}
              
              <button 
                type="button"
                onClick={handleNextStep}
                className="flex-1 bg-[#1c5a4b] hover:bg-[#16473b] text-white py-4 rounded-2xl font-bold text-sm shadow-lg shadow-[#1c5a4b]/20 transition-all flex items-center justify-center gap-2"
              >
                {activeStep === modalSteps.length - 2 ? (
                  <>Confirm Request </>
                ) : (
                  <>Continue </>
                )}
              </button>
            </div>
            )}

          </div>
        </div>
      )}

      {/* Verbatim layout descriptor */}
      <footer className="text-center py-10 text-slate-400 text-xs font-semibold border-t border-slate-100 mt-20 max-w-7xl mx-auto">
        Interactive template referencing layout parameters of image_f7e8e7.png
      </footer>
    </div>
  );
}
export default PremiumServices;